"""
report_pdf.py
-------------
Generates a professional geotechnical PDF report using ReportLab.
Includes:
- Cover page
- RMR breakdown table
- Q-System breakdown table
- GSI breakdown
- Support recommendations
- Embedded charts
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)
import tempfile


class PDFReport:
    """
    Creates a premium geotechnical PDF report.
    """

    def __init__(self, results):
        """
        Args:
            results: ClassificationResult object.
        """
        self.results = results
        self.styles = getSampleStyleSheet()

    def generate(self, path: str):
        """
        Generate the PDF report.

        Args:
            path: Output file path.
        """
        doc = SimpleDocTemplate(path, pagesize=A4)
        elements = []

        # Cover Page
        elements.append(
            Paragraph("<b>Rock Mass Classification Report</b>", self.styles["Title"])
        )
        elements.append(Spacer(1, 20))
        elements.append(
            Paragraph(
                "Generated by RockMass Classification Tool", self.styles["Normal"]
            )
        )
        elements.append(Spacer(1, 40))

        # RMR Table
        elements.append(Paragraph("<b>RMR Breakdown</b>", self.styles["Heading2"]))
        rmr_table = self._create_table(self.results.rmr_breakdown)
        elements.append(rmr_table)
        elements.append(Spacer(1, 20))

        # Q-System Table
        elements.append(Paragraph("<b>Q-System Breakdown</b>", self.styles["Heading2"]))
        q_table = self._create_table(self.results.q_breakdown)
        elements.append(q_table)
        elements.append(Spacer(1, 20))

        # GSI Table
        elements.append(Paragraph("<b>GSI Breakdown</b>", self.styles["Heading2"]))
        gsi_table = self._create_table(self.results.gsi_breakdown)
        elements.append(gsi_table)
        elements.append(Spacer(1, 20))

        # Support Recommendations
        elements.append(
            Paragraph("<b>Support Recommendations</b>", self.styles["Heading2"])
        )
        support_table = self._create_table(self.results.support_recommendations)
        elements.append(support_table)
        elements.append(Spacer(1, 20))

        doc.build(elements)

    def _create_table(self, data: dict):
        """
        Create a styled table from a dictionary.

        Args:
            data: Dictionary of values.

        Returns:
            ReportLab Table object.
        """
        table_data = [["Parameter", "Value"]]
        for key, value in data.items():
            table_data.append([key, str(value)])

        table = Table(table_data)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONT", (0, 0), (-1, -1), "Helvetica"),
                    ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
                ]
            )
        )
        return table
